name: metronome
description: A realistic metronome application
publish_to: 'none'

version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  yaml: ^3.1.2
  path: ^1.8.3
  args: ^2.4.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app/logo.png"

flutter_native_splash:
  color: "#0D0D1A"
  image: assets/app/logo.png
  android_12:
    color: "#0D0D1A"
    image: assets/app/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/app/